name: Workshop University
on:
  push:
    branches:
      - dev_arm
    paths-ignore:
      - 'docs/**'

jobs:
  Build:
    runs-on: ubuntu-24.04-arm64
    strategy:
      matrix:
        build_type: [arm]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set env variables
        run: |
          type=$( echo ${{ matrix.build_type }} | tr 'a-z' 'A-Z')
          echo ARTIFACT_NAME=ftc25_"${{ matrix.build_type }}" >> $GITHUB_ENV
      - name: Build image
        run: |
          sudo apt-get update
          # remove container if already exists
          CONTAINER_NAME=$(grep -m1 -oP '^[#]?CONTAINER_NAME=\K.*' ./config)
          if [ "$(docker ps -a -q -f name=^/${CONTAINER_NAME}$)" ]; then
              docker rm -fv "$CONTAINER_NAME"
          fi

          rm config && mv config-${{ matrix.build_type }} config
          sudo bash build-docker.sh
          ls kuiper-volume/*.zip >/dev/null 2>&1 && exit 0 || exit 2
      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}_image
          path: ${{ github.workspace }}/kuiper-volume/*.zip
      - name: Upload meta
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}_meta
          path: |
            ${{ github.workspace }}/kuiper-volume
            !${{ github.workspace }}/kuiper-volume/*.zip
